---
- name: Copy the flannel configuration script
  template: src=config-flannel.sh.j2 dest=~/config-flannel.sh mode=755

- name: Run the flannel configuration script
  command: ~/config-flannel.sh

- name: Remove the configuration script
  file: name=~/config-flannel.sh state=absent
